links: clean
	ln -s libsfml-system.so.2.1 libsfml-system.so.2
	ln -s libsfml-window.so.2.1 libsfml-window.so.2
	ln -s libsfml-audio.so.2.1 libsfml-audio.so.2
	ln -s libsfml-graphics.so.2.1 libsfml-graphics.so.2
	ln -s libsfml-system.so.2.1 libsfml-system.so
	ln -s libsfml-window.so.2.1 libsfml-window.so
	ln -s libsfml-audio.so.2.1 libsfml-audio.so
	ln -s libsfml-graphics.so.2.1 libsfml-graphics.so

clean:
	rm libsf*.so libsf*.so.2;